### ISSUE TITLE
Installation error -- possibly undefined macro AC_MSG_RESULT

### ISSUE THREAD

**Issue by bountonw** [tlwg/libdatrie#18]
Running `./autogen.sh` results in the following error.

     configure.ac:120: error: possibly undefined macro: AC_MSG_RESULT
           If this token and others are legitimate, please use m4_pattern_allow.
           See the Autoconf documentation.

**Comment by pepa65** [comment]
Is this also a case of needing to install `autoconf-archive`?

**Comment by thep** [comment]
Yes, this is a duplication of issue #17.
