### ISSUE TITLE
Cannot install r0.2.10 on centos 7

### ISSUE THREAD

**Issue by songpr** [tlwg/libdatrie#7]
There is issue as show below
`
[root@61-90-188-123 libdatrie-r_0_2_10]# ./autogen.sh
+ DIE=0
+ libtoolize --version
+ LIBTOOLIZE=libtoolize
+ '[' 0 -eq 1 ']'
+ autoheader
+ libtoolize --force
libtoolize: putting auxiliary files in `.'.
libtoolize: linking file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: linking file `m4/libtool.m4'
libtoolize: linking file `m4/ltoptions.m4'
libtoolize: linking file `m4/ltsugar.m4'
libtoolize: linking file `m4/ltversion.m4'
libtoolize: linking file `m4/lt~obsolete.m4'
+ aclocal
+ automake --add-missing
configure.ac:30: installing './config.guess'
configure.ac:30: installing './config.sub'
configure.ac:10: installing './install-sh'
configure.ac:10: installing './missing'
Makefile.am: installing './INSTALL'
datrie/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
+ autoconf
configure.ac:117: error: possibly undefined macro: AC_MSG_RESULT
      If this token and others are legitimate, please use m4_pattern_allow.
`
But no issue with r0.2.9

`[root@61-90-188-123` libdatrie-r_0_2_9]# diff ./configure.ac ../libdatrie-r_0_2_10/configure.ac
5c5
< AC_INIT(libdatrie, 0.2.9, theppitak@gmail.com)
---
> AC_INIT(libdatrie, 0.2.10, theppitak@gmail.com)
17c17
< LT_REVISION=2
---
> LT_REVISION=3
116,121c116,118
<     if expr $DOXYGEN_VER \< $DOXYGEN_REQ_VER > /dev/null; then
<       AC_MSG_RESULT([$DOXYGEN_VER, no, documentation disabled])
<       enable_doxygen_doc="no"
<     else
<       AC_MSG_RESULT([$DOXYGEN_VER, yes])
<     fi
---
>     AX_COMPARE_VERSION([$DOXYGEN_VER],[ge],[DOXYGEN_REQ_VER],
>                        [AC_MSG_RESULT([$DOXYGEN_VER, yes])],
>                        [AC_MSG_RESULT([$DOXYGEN_VER, no, documentation disabled]); enable_doxygen_doc="no"])
`

**Comment by thep** [comment]
You need to install [autoconf-archive](https://www.gnu.org/software/autoconf-archive/) to get the `AX_COMPARE_VERSION` macro.

**Comment by thep** [comment]
As this is not actually a bug, just about a missing component on the building system, I'm closing it now.
