### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by legale** [tlwg/libdatrie#9]
If i add full 1-byte range from 0x00 to 0xff. TrieChar 255 appears int the results of trie_state_walkable_chars() or trie_enumerate(). 

1byte.abm
```
[0x0,0xff]
```

```
trietool 1byte add 12
trietool 1byte add 122
trietool 1byte list
12ÿ	-1
122	-1
ru@ru-mi:/usr/local/libdatrie/bin# 
```

**Comment by thep** [comment]
This appears to be a bug in `AlphaMap` where trie char 0 is incorrectly mapped to 255 (`0xff`) due to an overflow in `alpha_map_recalc_work_area()`, similar to Issue #6.

I'm fixing it soon.
